spring:
  profiles:
    active: local # 기본 환경 선택
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

# local H2 환경
---
spring:
  profiles: local
  datasource:
    data: classpath:data-h2.sql # 시작할때 실행시킬 script
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

# dev 개발 환경
---
spring.profiles: dev
spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://betterfly-sql.creacra6qvrv.ap-northeast-2.rds.amazonaws.com:3306/themejoo_dev?useSSL=false&autoReconnect=true&characterEncoding=UTF-8
      username: betterfly
      password: betterfly

server:
  port: 8081

# prd 배포 환경
---
spring.profiles: prd
spring.profiles.include: prd-db

server:
  port: 8082