---
spring:
  profiles: prd-db
  datasource:
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://betterfly-sql/themejoo_dev?useSSL=false&autoReconnect=true&characterEncoding=UTF-8